# This is a basic workflow to help you get started with Actions

name: actions-testing
on:
  workflow_dispatch:
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          curl -H Metadata:true http://169.254.169.254/metadata/instance?api-version=2017-03-01
